### ISSUE TITLE
Исправить etcdWatch

### ISSUE THREAD

**Issue by max107** [mimicloud/mimi-proxy#1]
При выполнении `etcdctl set /apps/u1/backends/b1 '{"url": "localhost:8000"}'` не удаляется старый backend

**Comment by max107** [comment]
backend теперь удаляется, осталось исправить 
```
./mimi-proxy -path="../config.json"                            (master) 
:8588 2015/01/01 19:41:18 server.go:49: Serving connections on [::]:8588, frontends: 0
:8588 2015/01/01 19:41:18 server.go:49: Serving connections on [::]:8587, frontends: 0
:8588 2015/01/01 19:41:18 server.go:101: Start error handler
:8588 2015/01/01 19:41:18 server.go:101: Start error handler
panic: runtime error: index out of range

goroutine 26 [running]:
runtime.panic(0x76c3e0, 0x9c67fc)
	/usr/local/go/src/pkg/runtime/panic.c:279 +0xf5
main.watchApps(0xc20804e000, 0xc20800090c, 0x4, 0xc20802c850, 0xc20802c8c0)
	/home/max/mimi-proxy/etcd.go:165 +0x1165
created by main.main
	/home/max/mimi-proxy/main.go:85 +0x2d8

goroutine 16 [IO wait]:
net.runtime_pollWait(0x7fe1795557d8, 0x72, 0x0)
	/usr/local/go/src/pkg/runtime/netpoll.goc:146 +0x66
net.(*pollDesc).Wait(0xc20802ca00, 0x72, 0x0, 0x0)
	/usr/local/go/src/pkg/net/fd_poll_runtime.go:84 +0x46
net.(*pollDesc).WaitRead(0xc20802ca00, 0x0, 0x0)
	/usr/local/go/src/pkg/net/fd_poll_runtime.go:89 +0x42
net.(*netFD).accept(0xc20802c9a0, 0x87c158, 0x0, 0x7fe179554418, 0xb)
	/usr/local/go/src/pkg/net/fd_unix.go:419 +0x343
net.(*TCPListener).AcceptTCP(0xc20803a200, 0x7fe1793c5cb0, 0x0, 0x0)
	/usr/local/go/src/pkg/net/tcpsock_posix.go:234 +0x5d
net/http.tcpKeepAliveListener.Accept(0xc20803a200, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/pkg/net/http/server.go:1947 +0x4b
net/http.(*Server).Serve(0xc208004de0, 0x7fe179555c38, 0xc20803a200, 0x0, 0x0)
	/usr/local/go/src/pkg/net/http/server.go:1698 +0x91
net/http.(*Server).ListenAndServe(0xc208004de0, 0x0, 0x0)
	/usr/local/go/src/pkg/net/http/server.go:1688 +0x14d
main.(*ApiServer).ListenAndServe(0xc20800e600, 0xc2080008f0, 0xe)
	/home/max/mimi-proxy/api.go:303 +0x732
main.main()
	/home/max/mimi-proxy/main.go:92 +0x33f

goroutine 19 [finalizer wait]:
runtime.park(0x420350, 0x9cce70, 0x9ca8c9)
	/usr/local/go/src/pkg/runtime/proc.c:1369 +0x89
runtime.parkunlock(0x9cce70, 0x9ca8c9)
	/usr/local/go/src/pkg/runtime/proc.c:1385 +0x3b
runfinq()
	/usr/local/go/src/pkg/runtime/mgc0.c:2644 +0xcf
runtime.goexit()
	/usr/local/go/src/pkg/runtime/proc.c:1445

goroutine 30 [IO wait]:
net.runtime_pollWait(0x7fe179555678, 0x72, 0x0)
	/usr/local/go/src/pkg/runtime/netpoll.goc:146 +0x66
net.(*pollDesc).Wait(0xc20802cae0, 0x72, 0x0, 0x0)
	/usr/local/go/src/pkg/net/fd_poll_runtime.go:84 +0x46
net.(*pollDesc).WaitRead(0xc20802cae0, 0x0, 0x0)
	/usr/local/go/src/pkg/net/fd_poll_runtime.go:89 +0x42
net.(*netFD).accept(0xc20802ca80, 0x87c158, 0x0, 0x7fe179554418, 0xb)
	/usr/local/go/src/pkg/net/fd_unix.go:419 +0x343
net.(*TCPListener).AcceptTCP(0xc20803a218, 0xc208027aa0, 0x0, 0x0)
	/usr/local/go/src/pkg/net/tcpsock_posix.go:234 +0x5d
net.(*TCPListener).Accept(0xc20803a218, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/pkg/net/tcpsock_posix.go:244 +0x4b
github.com/inconshreveable/go-vhost.(*VhostMuxer).run(0xc20801aa00)
	/home/max/go/src/github.com/inconshreveable/go-vhost/mux.go:104 +0x54
created by github.com/inconshreveable/go-vhost.NewVhostMuxer
	/home/max/go/src/github.com/inconshreveable/go-vhost/mux.go:67 +0xdc

goroutine 22 [runnable]:
net/http.(*persistConn).readLoop(0xc208029e40)
	/usr/local/go/src/pkg/net/http/transport.go:868 +0x829
created by net/http.(*Transport).dialConn
	/usr/local/go/src/pkg/net/http/transport.go:600 +0x93f

goroutine 23 [select]:
net/http.(*persistConn).writeLoop(0xc208029e40)
	/usr/local/go/src/pkg/net/http/transport.go:885 +0x38f
created by net/http.(*Transport).dialConn
	/usr/local/go/src/pkg/net/http/transport.go:601 +0x957

goroutine 27 [select]:
main.(*ApiServer).CheckAlive(0xc20800e600)
	/home/max/mimi-proxy/api.go:22 +0x10e
created by main.(*ApiServer).ListenAndServe
	/home/max/mimi-proxy/api.go:36 +0x81

goroutine 28 [IO wait]:
net.runtime_pollWait(0x7fe179555728, 0x72, 0x0)
	/usr/local/go/src/pkg/runtime/netpoll.goc:146 +0x66
net.(*pollDesc).Wait(0xc20802ca70, 0x72, 0x0, 0x0)
	/usr/local/go/src/pkg/net/fd_poll_runtime.go:84 +0x46
net.(*pollDesc).WaitRead(0xc20802ca70, 0x0, 0x0)
	/usr/local/go/src/pkg/net/fd_poll_runtime.go:89 +0x42
net.(*netFD).accept(0xc20802ca10, 0x87c158, 0x0, 0x7fe179554418, 0xb)
	/usr/local/go/src/pkg/net/fd_unix.go:419 +0x343
net.(*TCPListener).AcceptTCP(0xc20803a208, 0x0, 0x0, 0x0)
	/usr/local/go/src/pkg/net/tcpsock_posix.go:234 +0x5d
net.(*TCPListener).Accept(0xc20803a208, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/pkg/net/tcpsock_posix.go:244 +0x4b
github.com/inconshreveable/go-vhost.(*VhostMuxer).run(0xc20801a9b0)
	/home/max/go/src/github.com/inconshreveable/go-vhost/mux.go:104 +0x54
created by github.com/inconshreveable/go-vhost.NewVhostMuxer
	/home/max/go/src/github.com/inconshreveable/go-vhost/mux.go:67 +0xdc

goroutine 29 [chan receive]:
main.(*Server).ErrorHandler(0xc20802c850)
	/home/max/mimi-proxy/server.go:107 +0x108
created by main.(*Server).ListenAndServe
	/home/max/mimi-proxy/server.go:74 +0x335

goroutine 31 [chan receive]:
main.(*Server).ErrorHandler(0xc20802c8c0)
	/home/max/mimi-proxy/server.go:109 +0x435
created by main.(*Server).ListenAndServe
	/home/max/mimi-proxy/server.go:74 +0x335
```
